trigger:
- main

pool:
  name: agent-pool   # Replace 'Default' with the name of your self-hosted agent pool
  demands:
    - agent.name -equals <azure-agent> # Optional: Target a specific agent if needed

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
