version: '3.8'

services:
  app:
    image: charbelba/erp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ERP_DataBase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123@BH546Meet5@89#
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5044
    depends_on:
      - mysql
      - logstash
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123@BH546Meet5@89#
      MYSQL_DATABASE: ERP_DataBase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false  # Disable SSL for transport
    ports:
      - "9200:9200"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - backend


volumes:
  mysql-data:

networks:
  backend:




